# Generated by Django 4.0.3 on 2022-04-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feauture_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='housespace',
            options={'ordering': ['-room_meausure']},
        ),
        migrations.AddField(
            model_name='house',
            name='features',
            field=models.ManyToManyField(to='main_app.feature'),
        ),
    ]
